# SIA mascots for the 72x40 OLED (36x40 each), built on unicorn.py.
#   python3 spy_art.py          preview as text
#   python3 spy_art.py h > spy_art.h
#   python3 spy_art.py page     put the same art into page.h (between ART-BEGIN / ART-END)
import sys
from PIL import Image, ImageDraw
import unicorn
W, H, K = unicorn.W, unicorn.H, unicorn.K
P, E = unicorn.P, unicorn.E

def spy_unicorn(glint):
    """megaspy: the petbot unicorn wearing spy sunglasses."""
    big = Image.new("L", (W * K, H * K), 0)
    base = unicorn.draw(False).resize((W * K, H * K), Image.NEAREST)
    big.paste(base)
    d = ImageDraw.Draw(big)
    # sunglasses: a big dark lens over the eye, a bridge and a strap round the head
    d.rounded_rectangle(E(18.6, 13.8, 25.6, 19), radius=2 * K, fill=0)
    d.line(P((25.4, 15.6), (28.6, 16.4)), fill=0, width=int(1.0 * K))    # bridge to the far lens
    d.line(P((18.8, 15.2), (16.2, 14.6)), fill=0, width=int(1.0 * K))    # strap
    out = big.resize((W, H), Image.BOX).point(lambda v: 255 if v >= 128 else 0)
    # lens glint: two white pixels that slide across the lens
    gx = 20 + glint
    for x, y in ((gx, 15), (gx + 1, 16)):
        if 19 <= x <= 24:
            out.putpixel((x, y), 255)
    return out

def spy_agent(glint):
    """spyhunter: a classic spy in a fedora, coat collar up, dark glasses."""
    im = Image.new("L", (W * K, H * K), 0)
    d = ImageDraw.Draw(im)
    # coat with a tall collar
    d.polygon(P((3, 40), (7, 29), (13, 26), (23, 26), (29, 29), (33, 40)), fill=255)
    d.polygon(P((11, 26.5), (18, 36), (25, 26.5), (22.5, 26), (18, 31), (13.5, 26)), fill=0)   # lapels/V
    d.polygon(P((8.5, 29), (12, 21.5), (14, 27)), fill=255)                                   # left collar
    d.polygon(P((27.5, 29), (24, 21.5), (22, 27)), fill=255)                                  # right collar
    # face
    d.ellipse(E(11, 10, 25, 27), fill=255)
    # fedora: brim + crown with a band
    d.rounded_rectangle(E(4, 10, 32, 13), radius=1.5 * K, fill=255)
    d.polygon(P((9, 11), (10.5, 3), (18, 1.5), (25.5, 3), (27, 11)), fill=255)
    d.line(P((9.4, 8.6), (26.6, 8.6)), fill=0, width=int(1.4 * K))
    d.line(P((16, 2.2), (18, 4.5), (20, 2.2)), fill=0, width=int(0.9 * K))                   # crown pinch
    # dark glasses
    d.rounded_rectangle(E(12.6, 15.2, 17.4, 18.6), radius=1.4 * K, fill=0)
    d.rounded_rectangle(E(18.6, 15.2, 23.4, 18.6), radius=1.4 * K, fill=0)
    # mouth: a sly smile
    d.arc(E(15, 19.5, 21.5, 24), 20, 160, fill=0, width=int(0.9 * K))
    out = im.resize((W, H), Image.BOX).point(lambda v: 255 if v >= 128 else 0)
    gx = 13 + glint // 2
    for x in (gx, gx + 6):
        out.putpixel((x, 16), 255)
    return out

FRAMES = {
    "UNICORN_SPY": [spy_unicorn(g) for g in range(4)],
    "AGENT_SPY": [spy_agent(g) for g in range(4)],
}

def preview(im):
    for y in range(H):
        print("".join("#" if im.getpixel((x, y)) else "." for x in range(W)))

if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "preview"
    if mode == "h":
        print("// SIA mascots for the 72x40 OLED. Generated by spy_art.py - edit that, not this.")
        print(f"#pragma once\n#define SPY_ART_W {W}\n#define SPY_ART_H {H}\n#define SPY_ART_FRAMES 4\n")
        for name, frames in FRAMES.items():
            for i, im in enumerate(frames):
                print(unicorn.xbm(im, f"{name}_{i}"))
            print(f"static const unsigned char* const {name}[SPY_ART_FRAMES] = {{" +
                  ", ".join(f"{name}_{i}" for i in range(4)) + "};\n")
    elif mode == "page":
        rows = lambda im: ",".join(f"'{int(''.join('1' if im.getpixel((x, y)) else '0' for x in range(W)), 2):09x}'" for y in range(H))
        js = "\n".join(f"const {name} = [" + ",\n  ".join("[" + rows(im) + "]" for im in frames) + "];" for name, frames in FRAMES.items())
        page = open("page.h").read()
        a = page.index("// ART-BEGIN") + len("// ART-BEGIN")
        b = page.index("// ART-END")
        open("page.h", "w").write(page[:a] + "\n" + js + "\n" + page[b:])
        print("page.h updated")
    else:
        for name, frames in FRAMES.items():
            print(name); preview(frames[1]); print()
