# SIA mascots for the 72x40 OLED (36x40 each), built from outfits.py (which builds on unicorn.py).
#   python3 spy_art.py          preview as text
#   python3 spy_art.py h > spy_art.h
#   python3 spy_art.py page     put the same art into page.h (between ART-BEGIN / ART-END)
import sys
from PIL import Image, ImageDraw
import unicorn
W, H, K = unicorn.W, unicorn.H, unicorn.K
P, E = unicorn.P, unicorn.E

import outfits

# Picked 2026-09-30 from design/outfit-options.html: megaspy #6 Ninja mask, spyhunter #7 Tuxedo.
def megaspy_frame(k):
    """megaspy: the petbot unicorn in a ninja mask; the mask tails flutter."""
    return outfits.unicorn_outfit("ninja", wave=k)


def spyhunter_frame(k):
    """spyhunter: the spy in a tuxedo and top hat; a glint slides across the shades."""
    out = outfits.agent_outfit("tuxedo")
    gx = 13 + k // 2
    if k:
        for x in (gx, gx + 6):
            out.putpixel((x, 16), 255)
    return out


FRAMES = {
    "UNICORN_SPY": [megaspy_frame(k) for k in range(4)],
    "AGENT_SPY": [spyhunter_frame(k) for k in range(4)],
}

def preview(im):
    for y in range(H):
        print("".join("#" if im.getpixel((x, y)) else "." for x in range(W)))

if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "preview"
    if mode == "h":
        print("// SIA mascots for the 72x40 OLED. Generated by spy_art.py - edit that, not this.")
        print(f"#pragma once\n#define SPY_ART_W {W}\n#define SPY_ART_H {H}\n#define SPY_ART_FRAMES 4\n")
        for name, frames in FRAMES.items():
            for i, im in enumerate(frames):
                print(unicorn.xbm(im, f"{name}_{i}"))
            print(f"static const unsigned char* const {name}[SPY_ART_FRAMES] = {{" +
                  ", ".join(f"{name}_{i}" for i in range(4)) + "};\n")
    elif mode == "page":
        rows = lambda im: ",".join(f"'{int(''.join('1' if im.getpixel((x, y)) else '0' for x in range(W)), 2):09x}'" for y in range(H))
        js = "\n".join(f"const {name} = [" + ",\n  ".join("[" + rows(im) + "]" for im in frames) + "];" for name, frames in FRAMES.items())
        page = open("page.h").read()
        a = page.index("// ART-BEGIN") + len("// ART-BEGIN")
        b = page.index("// ART-END")
        open("page.h", "w").write(page[:a] + "\n" + js + "\n" + page[b:])
        print("page.h updated")
    else:
        for name, frames in FRAMES.items():
            print(name); preview(frames[1]); print()
